### ISSUE TITLE
Bug al borrar un comentario con votos

### ISSUE THREAD

**Issue by SeilaPr** [Arquisoft/participationSystem3b#4]
Al intentar borrar un comentario con votos da error ya que "no hay acción" para la foreign key, es decir, no se borran los votos del comentario. He puesto un delete on cascade para que se borren los votos del comentario al borrar el comentario pero no funciona...

**Comment by Unioviedu** [comment]
También ocurre al borrar sugerencias o categorías, tenemos que hacer los delete a mano. Hoy me pongo a ello.
